services:
  - type: web
    name: evm-realtimechat-server
    runtime: node
    plan: free
    buildCommand: pnpm i
    startCommand: pnpm run dev
    envVars:
      - key: VITE_DEV_STATUS
        value: 3